### ISSUE TITLE
 EC agent was crashing post EKS upgrade due DNS lookup issues

### ISSUE THREAD

**Issue by palokam** [EC-Release/oci2#14]
EC agent was crashing post EKS upgrade (1.20) due DNS lookup issues for the changes  happened with the alpine base image

Please use a different base image that fix  the DNS issues

**Comment by ayasuda-ge** [comment]
closed & committed. https://github.com/EC-Release/oci2/commit/5f74563cb7767b5663c1ac0344683f0e3d729534 [palokam](https://github.com/palokam)
