### ISSUE TITLE
Traditional Mode-docker using 1728 agent: Gateway failed to run

### ISSUE THREAD

**Issue by pragyan111** [EC-Release/oci2#2]
For traditional mode existing service scenario, while running gateway using docker using 1728 agent getting error as  **docker: Error response from deamon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: v1beta.linux64.sh : no such file or directory: unknown**

**Comment by ramaraosrikakulapu** [comment]
Looking into the issue @pragyan111

**Comment by ramaraosrikakulapu** [comment]
@pragyan111 .. can you please reverify and update the result.

**Comment by pragyan111** [comment]
validated traditional mode using 1728 agent, gateway is running successfully using docker.

**Comment by ramaraosrikakulapu** [comment]
Thanks @pragyan111 for the verification 👍
